Add French language to dataset 🇫🇷
tomasz-oponowicz/spoken_language_dataset pull request #2
Opened 2018-07-19 14:16 UTC by nSimonFR

I have added some [Librivox](https://librivox.org/) recording to [speech.csv](speech.csv) in order to support the French language for the dataset. 
It's about ~650 minutes of audio, or about the same as the English dataset.

I have not included mirrors link pointing to another provider - so the recordings are being fetched directly from [archive.org](https://archive.org/), but I modified the fetch script so it prioritizes mirrors (As they are faster to download for me).

I also added a simple script for people who want to know the average recording length of the dataset for each language ([dataset-size.py](dataset-size.py)).

The main project -[ tomasz-oponowicz/spoken_language_identification](https://github.com/tomasz-oponowicz/spoken_language_identification) - might need to be tweaked in order to support the new language.

🇫🇷  🌟 🌟 🇫🇷

2018-07-19 18:47 UTC, tomasz-oponowicz commented
@nSimonFR Absolutely awesome job :) +1 I will review and merge it soon.

2018-07-22 15:13 UTC, tomasz-oponowicz requested changes
Looks good to me.

I found few minor things. Please take a look at my comments.

2018-07-22 15:13 UTC, tomasz-oponowicz commented on speech.csv
> +train,fr,female,mp3,Anne,00:05:27,http://www.archive.org/download/delespritdeslois_anlo_1004_librivox/delespritdeslois_05_08_montesquieu_64kb.mp3,
The training track has to be at least 5m 30s long. Is it possible to find a replacement?

2018-07-22 15:13 UTC, tomasz-oponowicz commented on speech.csv
> +train,fr,female,mp3,Claire Dyard,00:16:45,http://www.archive.org/download/le_pays_des_fourrures_0712_librivox/pays_fourrures_06_verne_64kb.mp3,
In order to keep all languages equally balanced we need 28 training tracks (14 males and 14 females). There are 27 training tracks now, i.e. one male track is missing.

2018-07-22 15:13 UTC, tomasz-oponowicz commented on speech.csv
> +train,fr,female,mp3,Jc Guan,00:43:54,https://ia800203.us.archive.org/16/items/comte_monte_cristo_jg_librivox/montecristo_036_dumas_64kb.mp3,
Can you replace `ia800203.us.archive.org` with `www.archive.org`? From my experience `*.archive.org` servers are temporary and may go down.

2018-07-23 16:11 UTC, nSimonFR commented
Hello Tomasz,
I have made the necessary changes, let met know if something still isn't right !

2018-07-23 19:59 UTC, tomasz-oponowicz approved these changes

2018-07-23 19:59 UTC, merged